### ISSUE TITLE
Travis badge

### ISSUE THREAD

**Issue by jjl** [mpg-project/mpg#11]
Travis sucks, but it sucks less than anything I don't have to host myself because I am lazy. My release manager is looking into how to fix travis builds that rely on postgres at the minute (because we need it for utrecht).

It would be nice to show off that our tests pass on a clean envrionment.

**Comment by jjl** [comment]
Kent has gotten to the bottom of it. Turns out to be quite easy to get postgres up on travis. https://github.com/irresponsible/utrecht/blob/ded2093b1ca2a09ad9cdd4a0b4662c8260d296e4/.travis.yml

**Comment by jjl** [comment]
I've had a look at the travis site and I don't have the requisite privileges to enable builds.

**Comment by JuneKelly** [comment]
I presume if we put the appropriate config in place and enable builds on Travis it should all Just Work?

If so I can set up Travis over the weekend.

**Comment by jjl** [comment]
If you copy and paste that config and tweak it to fit (e.g. utrecht downloads and installs boot, travis has leiningen built in), commit it as .travis.yml to master and flick the switch on travis-ci.org, yes, it should "just work"

**Comment by JuneKelly** [comment]
[aside: I've just enabled admin permissions on this repo for you account @jjl, thought I had done it earlier]

**Comment by jjl** [comment]
Haha, don't think that means I'm going to do _all_ the work :)

**Comment by JuneKelly** [comment]
Of course not ;)

But if I get hit by a bus, there'll be some admin continuity in the project.

**Comment by jjl** [comment]
Ah, yes. Well you should hack on some of the irresponsible stuff likewise :)

**Comment by JuneKelly** [comment]
Done: https://travis-ci.org/mpg-project/mpg
