### ISSUE TITLE
citext should not be saved as json

### ISSUE THREAD

**Issue by jjl** [mpg-project/mpg#13]
It is actually just a string type

**Comment by JuneKelly** [comment]
For reference: http://www.postgresql.org/docs/current/static/citext.html

**Comment by JuneKelly** [comment]
I've committed on branch `issue-13-citext`, would you mind taking a look and checking that the case is properly covered? I haven't used the citext type before, so I'm not sure if there's some quirk I'm not taking into account.

**Comment by jjl** [comment]
Looks pretty good to me :)

**Comment by jjl** [comment]
Just to elaborate: so far as I'm aware, the only time citext behaves differently from string is during comparison, so we can just treat it like a dumb string.

**Comment by JuneKelly** [comment]
Cool, will merge and release.

**Comment by jjl** [comment]
you may as well wait for #14, since that's going to be nailed today.

**Comment by JuneKelly** [comment]
Done
