### ISSUE TITLE
clojure.java.jdbc/insert! does not play nicely

### ISSUE THREAD

**Issue by jjl** [mpg-project/mpg#14]
And best of all, I get a different error from the reporter of the bug in irc.

I get a NullPointerException because `PgPreparedStatement.getMetaData()` returns null. The utterly quality [pgjdbc code](https://gist.github.com/jjl/7cbbebdf8268baa66222fdf476974aa3) this goes through is not enlightening. Anyway, it appears .getMetaData is returning null inside an insert! which is breaking everything.

The probable outcome of this will be fixes to clojure.java.jdbc :/

**Comment by jjl** [comment]
Okay, so it looks like we don't have enough information to proceed on when we're doing an insert.

My next step will be to figure out whether it's a quirk of clojure.java.jdbc or pgjdbc. From then on, I have to decide whether to patch it there or work around it here or both.

My suspicion is that the jdbc api doesn't give us enough information to work it out and that we have to default to the default map type in our code, which is a bit of a hack. I'll report back when I've investigated further

**Comment by JuneKelly** [comment]
Merged #15, Going to leave this issue open
