### ISSUE TITLE
bytea support

### ISSUE THREAD

**Issue by jjl** [mpg-project/mpg#16]
http://www.postgresql.org/docs/current/static/datatype-binary.html

bytea <-> Bytebuffer?

**Comment by jjl** [comment]
Relevant for implementation: [yesql issue](https://github.com/krisajenkins/yesql/issues/122)

**Comment by ilevd** [comment]
To select binary data it needs to return a string rather than a raw binary blob: http://www.postgresql.org/docs/9.5/static/functions-binarystring.html, eg SELECT encode(bytea, 'hex')

**Comment by jjl** [comment]
unbefuckinglievable this, but yesql has turned off their github issue tracker so we can't actually see the discussion they had about it at the time.

As for bytea support, well apparently it just works(tm). see [my bytea branch](https://github.com/mpg-project/mpg/tree/bytea) for passing tests. very confusing!

**Comment by jjl** [comment]
As it just works, I think this counts as closeable. The tests are in the PR I just made
