### ISSUE TITLE
Queries dependent upon PG array data type work first time but fail on subsequent calls

### ISSUE THREAD

**Issue by cwyckoff** [mpg-project/mpg#17]
_The following problem description references the mpg code found here: "mpg/src/mpg/data.clj:56-64"._

When querying a Postgres array of strings (varchar[]), the initial query works, but all subsequent queries throw the following error: 'org.postgresql.util.PSQLException: ERROR: column "<column-name>" is of type character varying[] but expression is of type json. Hint: You will need to rewrite or cast the expression.'.  A little investigation revealed that calling `.getParameterTypeName` on a JDBC `ParameterMetaData` object from a new `PreparedStatement` object returns "_varchar".  This is an expected response for the mpg implementation of IPersistentVector#'set-parameter, which then uses "varchar" as the element type to create an array object that gets set on the `PreparedStatement` object.  Once that array is set on the `PreparedStatment,` however, subsequent calls to get the parameter type name from the `ParameterMetaData` return "varchar[]".  This is true for new instances of `PreparedStatment` objects using the same sql string and db connection. As a result, mpg's implementation of `IPersistentVector#'set-parameter` defaults to setting a JSON object instead of an array on the `PreparedStatement.`  Hence, the Postgres error mentioned above. Since `PreparedStatement` objects seem to be cached (for the life of the database connection?) and reused with different query params, some changed state in the `PreparedStatement` object affects all future queries of that sql statement until the db connection is reset.  Updating the sql statement to specify data type (i.e., `<field-name>::varchar[]`) doesn't seem to have an effect.

You can reproduce the issue with the following steps:

1) with postgres running, create a new database.
`createdb repro_bug`

2) at a terminal window type:
`psql repro_bug -c 'create table foo (bar character varying(255)[])'`

3) then evaluate the clojure code in the following gist: https://gist.github.com/cwyckoff/faa1cad80b64b726a4900f6fd30c841d

**Comment by JuneKelly** [comment]
Will take a look in the next few days.

Do you have a work-around in place?

**Comment by cwyckoff** [comment]
Sorry for the late response.  We have been using our own database util fn to convert between PG and clj datatypes and were hoping to use mpg to replace that.  So, at the moment we are sticking w/ the homegrown solution.

**Comment by JuneKelly** [comment]
@cwyckoff no worries :)

I'm hoping to get a chance to look at this over the weekend.

**Comment by JuneKelly** [comment]
I may be thinking about this entirely wrong, but it looks like we need to cache the result of the first call to `.getParameterTypeName`, then re-using that value on subsequent invocations.

If I'm wrong on that, someone correct me, I have no idea what I'm doing.

**Comment by JuneKelly** [comment]
This issue _may_ be solved on the `issue-17` branch: https://github.com/mpg-project/mpg/tree/issue-17

Would appreciate some testing, as it's a speculative fix, and I'm not sure it'll actually solve the problem.

**Comment by cwyckoff** [comment]
Great.  I'll check it out and test tonight or later this weekend.  Appreciate the quick turnaround!

**Comment by cwyckoff** [comment]
@ShaneKilkelly, Tested your fix out and it worked for our problem case.  Nice work!

**Comment by jjl** [comment]
Edit: nevermind, I reread the above and spotted you'd already addressed this. Need more coffee.

**Comment by JuneKelly** [comment]
@cwyckoff thanks,

I'll merge to master and cut a new release.

**Comment by JuneKelly** [comment]
mpg version 1.1.0 is live on clojars: https://clojars.org/mpg/versions/1.1.0

Closing issue, thanks everyone!
