### ISSUE TITLE
clojure.java.jdbc vs clojure.jdbc

### ISSUE THREAD

**Issue by csummers** [mpg-project/mpg#2]
It looks like your library targets the `clojure.java.jdbc` library, but your documentation and announcements say `clojure.jdbc`.   These are two separate libraries, so this is bound to add to the confusion that already exists.  You should change any reference from `clojure.jdbc` to `clojure.java.jdbc`.

[clojure.java.jdbc](https://github.com/clojure/java.jdbc)
[clojure.jdbc](https://github.com/funcool/clojure.jdbc)

Thanks for the library.  I think it does meet a need for postgresql boilerplate.

**Comment by JuneKelly** [comment]
Thanks, good catch!

Will get this fixed asap.

**Comment by JuneKelly** [comment]
I believe this issue is now fixed, thanks for bringing it to my attention!
