### ISSUE TITLE
Do we want more unidirectional casts?

### ISSUE THREAD

**Issue by jjl** [mpg-project/mpg#22]
By this, I mean do we want to be able to accept as input something that we could convert to a given column, but not be able to generate as output?

Examples:
1. I can (as of pull requests) pass in a byte-array for a bytea and get one back out when it is queried. Do we want to be able to pass in a ByteBuffer, even though we will not generate one from a bytea field?
2. There are other date and time types in the standard library that we could use

Further question: do some of these indicate we should have some more options like `:default-map`? I am loathe to make it so easy to shoot yourself in the foot with DateTime-y things, but I can also see a valid use case for wanting e.g. java.util.Date even though it gives us a massive caveat

**Comment by JuneKelly** [comment]
I suppose we should hew toward being useful, even if it means a less-than-perfect api. If the uni-directional casts are documented properly, so the developer won't be suprised by the behaviour, then I have no objection to implementing them.

Conversly, I also have no concrete objection to telling the developer they must marshal their data before it goes into the database.

**Comment by jjl** [comment]
Arguments for: developers write slightly less code
Arguments against: could be confusing.

I am inclined to say "let's do it", but also I think we should crowdsource a list of candidates

**Comment by jjl** [comment]
I'll kick us off

```
java.util.Date
java.nio.ByteBuffer
```

**Comment by jjl** [comment]
Still crowdsourcing candidates. @ShaneKilkelly - any ideas?

**Comment by JuneKelly** [comment]
No concrete suggestions, Date and ByteBuffer seem like good places to start, and we can always add more :)

**Comment by jjl** [comment]
See PR #24
