### ISSUE TITLE
Abstraction holes

### ISSUE THREAD

**Issue by jjl** [mpg-project/mpg#26]
As I alluded to in my last ticket, I'm aware that there are some holes in our abstraction and I want to plug them. See the discussion on this commit:
https://github.com/enragedginger/mpg/commit/61375966f3f58ad693375ad3026d701cad2ebec0

Firstly, I'd like to gather a list of what is falling through. @enragedginger - is it possible you could log anything that goes through the default case on your app? it would be really handy to figure out what's going wrong - i'm not deploying anything busy enough to flush it out until early next year.

**Comment by enragedginger** [comment]
I'm seeing a stacktrace which looks something like this:

```
java.lang.IllegalArgumentException: No matching clause: int4
        at mpg.data$patch$fn__3627.invokePrim(data.clj:47)
        at mpg.data$patch$fn__3627.invoke(data.clj)
        at clojure.java.jdbc$eval1403$fn__1404$G__1394__1413.invoke(jdbc.clj:345)
        at clojure.java.jdbc$set_parameters$fn__1500.invoke(jdbc.clj:506)
        at clojure.core$map_indexed$mapi__7050$fn__7051.invoke(core.clj:7022)
        at clojure.lang.LazySeq.sval(LazySeq.java:40)
        at clojure.lang.LazySeq.seq(LazySeq.java:49)
        at clojure.lang.RT.seq(RT.java:521)
```

It's happening while writing a map of type `clojure.lang.PersistentArrayMap` which contains integer values to a table with a `jsonb` column. Something like this: `{"key1" {"key2" 5}}` should trigger it.

I'm on:
- Clojure 1.8
- `[mpg "1.2.0"]`
- `[org.clojure/java.jdbc "0.6.2-alpha2"]`
- `[org.postgresql/postgresql "9.4.1209"]`

Do you need any more information?

**Comment by jjl** [comment]
I'm going to put some time into reproducing this in the coming week. I'll let you know how I get on. Cheers :)

**Comment by clukey** [comment]
I've run into the same issue this week. Depending on which fields I include or leave out of the map to insert, it will fail with "No matching clause" for text, varchar, or int8. The stack trace is otherwise identical to enragedginger's.

We have a table like so:

``` sql
CREATE TABLE providers (
id serial PRIMARY KEY,
client_id BIGINT,
provider_type TEXT,
example_field CHARACTER VARYING(255),
config JSON,
created_at TIMESTAMP DEFAULT NOW(),
updated_at TIMESTAMP
);
```

and we're attempting an insert:

``` clojure
(jdbc/insert! connection-uri :providers {:client_id 2 :provider_type "foo" :config {:foo "bar"}})
```

using 

[org.clojure/clojure "1.8.0"]
[mpg "1.2.0"]
[org.clojure/java.jdbc "0.6.2-alpha3"]
[org.postgresql/postgresql "9.4.1211"]

**Comment by jjl** [comment]
Sorry for the delay, I've been putting epic amounts of effort into getting a release out for another (postgres! clojure!) module, but I'm finally working on replicating these as failing tests so I can know I've fixed it :)

**Comment by jjl** [comment]
Well, that was an adventure, and that's another 8 hours of my life lost to JDBC.

Once again I find myself probing the black box. I have written tests that replicate this behaviour (PR coming along in a few minutes). I have fixed said tests. I have no idea how the fuck, why the fuck or what the fuck black magic is going on here.

I am starting to feel that entrusting one's data to JDBC is a fool's game...

**Comment by jjl** [comment]
Resolved by PR #27. Please test it in your codebases and see if it fixes things for you!

**Comment by jjl** [comment]
Oh, since we've switched to boot, if you want a jar before @ShaneKilkelly gets around to a release, you can run `boot pom jar install`, but change the version first, to e.g. `1.3.0-TRIAL` so you can identify it.

**Comment by enragedginger** [comment]
@jjl Thanks so much for doing this. It sounds like it wasn't easy. Can you comment a bit on the rationale of the changes? I think I understand it for the most part, but I'm not entirely sure.

**Comment by jjl** [comment]
Hi @enragedginger,

What seemed to have been happening in my debugging was something like this:
1. Protocol would be called back for the map, against the IPersistentMap implementation
2. Protocol would be called back for each value of the map (but not key?), against the IPersistentMap implementation.

I honestly have no idea how what i've done fixes things, but the tests didn't pass and now they pass. Anyone with more experience with JDBC is more than welcome to wade in and do a better job :)

**Comment by jjl** [comment]
Oh, incidentally there are a couple of new functions in `mpg.util` (`param-meta`, `result-meta`) which dump information about what types the parameters/results of the `PreparedStatement` are. They're really useful for debugging.

While doing the above incidentally, I noticed the difference between parameter and resultset metadata. Because we used postgres (where resultsets from inserts are the full rows rather than the ids), ours always worked by accident, but now it works according to JDBC.

**Comment by jjl** [comment]
Oh and on travis (but notably not on my local machine which runs pg 9.5, not the 9.4 available on travis), postgres started complaining about passing it `json` data to a `jsonb` column, hence the addition of the extra 'default' option and the separate handling of the two types.

**Comment by clukey** [comment]
I'm excited to check it out!

**Comment by enragedginger** [comment]
@jjl Thanks for the explanation. That makes sense to me.

**Comment by jjl** [comment]
Well I hope it works for you this time @clukey @enragedginger :)

**Comment by JuneKelly** [comment]
Sorry guys, having a really hard time figuring out how to deploy to clojars with boot. Will hopefully get it sorted by tomorrow.

**Comment by JuneKelly** [comment]
Actually, I've just re-added the `project.clj` file to make it possible to deploy with `lein`, will figure boot out later. Version 1.3.0 is live on Clojars.

Thanks everyone!

**Comment by jjl** [comment]
Actually I've got vague memories of doing the same thing when I first moved over to boot. Also to generate docs and things (there just weren't the plugins back then...) ;)

**Comment by enragedginger** [comment]
I just re-ran my project with version 1.3.0. Everything appears to be working properly. I'll need to do some data integrity checks just to be sure, but for now, it looks like everything is fixed.

Thank you!

**Comment by clukey** [comment]
Sorry it took me so long to respond, but it's working great so far. Thanks for the fix!
