### ISSUE TITLE
Consider: users may want clj-time/joda-time instead of java.util.Date

### ISSUE THREAD

**Issue by JuneKelly** [mpg-project/mpg#3]

**Comment by jjl** [comment]
Or possibly also [java.time](https://github.com/dm3/clojure.java-time)

**Comment by JuneKelly** [comment]
@jjl indeed. If we could restrict to JRE 8+ then that would work.

If anyone watching this issue has any suggestions, feel free to put them forward, as I have no idea what the right move would be.

**Comment by jjl** [comment]
I'm currently locally experimenting on a rewrite that uses the java 8 api

Java 7 is EOL now and this is a new module. I'd suggest that you shouldn't be encouraging people to accrue technical debt. None of my modules support lower than 1.8 officially any more though people are welcome to try their luck.

I'm also amused by the idea that you might want to use a modern postgres with an old JVM.

**Comment by JuneKelly** [comment]
I'm in broad agreement with all your points.

If you want to submit a pull-request based on your experiment some time that would be cool.

**Comment by jjl** [comment]
Things I've learned so far from playing around:
- The Java 8 Time api is annoying
- The postgres driver has changed the name of the arrays class as well as the naming convention for artifacts
- An ideal api for triggering the setup would be a function call that takes a list of mappings _not_ to establish. This allows users to selectively opt-out
- The default unknown type (PGobject) requires us to handle several cases. I'm thinking we should probably keep them in an atom so we can update them at any time.

Thoughts?

**Comment by JuneKelly** [comment]
I think a function call that would accept parameters could be the right way to go:

```
(ns whatever.db
    (require [clojure.java.jdbc :as j]
             [jdbc-pg-sanity.core :as sanity]))

(sanity/patch! {:some-option true})
```

**Comment by jjl** [comment]
okay, i've spent waaaaaaaaayyyyyyy too much time playing with this the last couple of days but I think I've got a good understanding of the drawbacks of a few approaches.

The primary complication seems to arise from the fact that vectors and maps map to multiple postgres datatypes. In particular, vector, which requires totally separate handling depending on whether it's going into an array column or a json/jsonb.

I played around with controlling which directions conversions are performed with etc. and i think the only reasonable approach is controlling it on a clojure/java type basis. I'd favour an opt-out basis, but I don't feel particularly strongly about it.

The categories I'm proposing are:

```
:vector - vector <-> array,json,jsonb
:map - map <-> json,jsonb
:date - java.time.LocalDate <-> date
:time - java.time.Instant <-> timestamp, java.time.ZonedDateTime <-> timestamptz
```

There are a whole load of other java.time classes [here](https://docs.oracle.com/javase/8/docs/api/java/time/package-summary.html) that we could probably install conversions for, but I'm claiming zero experience with the java.time api at this point and I'm hoping somebody who does will come in with some wisdom.

My patch is nearly complete. Let me know your thoughts

James

**Comment by JuneKelly** [comment]
Yeah, it all seems very sensible, and I think you have a better handle on the issues here than I do at this point.

I also didn't realise an array/vector is a valid top-level jsonb entity, I can see why that would complicate things.

**Comment by jjl** [comment]
okay. well i'll finish it up this afternoon and submit a PR. Can you get a new release out today? :)

**Comment by JuneKelly** [comment]
I may be able to, depending on when I can review the PR. I'm confident it'll all go smoothly, so it shouldn't take long, just need to do the release to clojars :)

**Comment by jjl** [comment]
Hrm. Since we're changing the api completely. perhaps we can use this opportunity to pick a slightly less annoying namespace and artifact name? :)

**Comment by jjl** [comment]
i nominate 'mpg' with tagline 'more modern postgres to the gallon'

**Comment by JuneKelly** [comment]
Re: namespace

Yeah, you have a point. `mpg` seems good, it's unique and sufficiently abstract :) I think I'll publish the new release under that name once it's gone out under the current one.

EDIT: I'll be available until about 17:30 UTC today, after which I'll be away for the evening. Will endevour to get a release out before then.

**Comment by jjl** [comment]
cool :) I'll update the docs in my patch. I think github has support for renaming repos with forwarding now, but you'll probably want to submit an update to clojure-toolbox

**Comment by jjl** [comment]
Actually there's a bit more complication that I didn't mention:
- citext. I don't actually know what this is, but i'm guessing it's a form of string. we cover this in json decode regardless of opt-out
- json containing vectors we will quietly read, but not write.

I'm thinking that :data should cover vectors and maps, :datetime should cover dates and times. Can you clue me in on what citext is?

**Comment by JuneKelly** [comment]
No idea what citext is, sorry.

One more wrinkle I've just thought of: if we read out json(b) columns and pass them through a json->clj parser, won't that cover the case where the json(b) object is an arrary? I would expect that should just work transparently.

**Comment by jjl** [comment]
yes, you understand correctly. the "problem" is that it unexpectedly works, but only in one direction. I'm going to lump maps and vectors together to simplify it.

**Comment by JuneKelly** [comment]
Ah, cool. I'll cede to your judgement on this, you seem to have studied the issue more closely than I have :)

**Comment by jjl** [comment]
That's a generous way of putting 'getting repeatedly confused by the jdbc api' :)

**Comment by JuneKelly** [comment]
I think this issue has been addressed with the recent PRs. Closing for now, can re-open if it becomes an issue again.
