### ISSUE TITLE
hstore support, internal representations

### ISSUE THREAD

**Issue by jjl** [mpg-project/mpg#5]
As detailed in PR #4, I've added limited hstore support. There is a question of what we should do with hstore because it is a bit inconsistently treated compared to json. cheshire unpicks keywords and such when they are keys in maps. That's rather nice, should we try to emulate it? On the other hand, we can't even have actual numbers because jdbc boxes it into HashMap<String,String>

**Comment by jjl** [comment]
Since it's a new module, we don't have a legacy userbase to support who need more than basic HSTORE support. I'd say we should probably leave it as-is for now and if someone wishes to contribute better HSTORE support later, let them.

**Comment by JuneKelly** [comment]
I'm fine with that :)

**Comment by jjl** [comment]
Brilliant. Closing.
