### ISSUE TITLE
License conflict

### ISSUE THREAD

**Issue by jjl** [mpg-project/mpg#7]
The README and the project.clj say it's MIT-Licensed, but the LICENSE file is way too long for that. Looks vaguely like the Eclipse License from memory.

What is it _supposed_ to be licensed under?

**Comment by JuneKelly** [comment]
Ah, it's supposed to be MIT.

I'm constantly being bitten by this issue, `lein` just vomits out a template with some bizarro Eclipse License.

Will correct it.

**Comment by JuneKelly** [comment]
Fixed in ffbe0caecf54a3d2564b18340cd522bb691d1143

**Comment by jjl** [comment]
Ah. Yeah, I've taken to not generating skeletons, to just mkdir -p the longest directory in the thing and then copy a build.boot from other projects :)
